// ============================================================
// Hotels Vendors — Marketing Content Data
// ============================================================

// ------------------------------------------------------------------
// 1. CAROUSEL SLIDES
// ------------------------------------------------------------------
export interface CarouselSlide {
  id: string;
  portal: 'hotel' | 'supplier' | 'marketplace' | 'admin';
  headline: string;
  subtext: string;
  ctaPrimary: { label: string; href: string };
  ctaSecondary: { label: string; href: string };
  stats: { value: string; label: string }[];
  gradientFrom: string;
  gradientTo: string;
}

export const carouselSlides: CarouselSlide[] = [
  // Hotel Portal — 3 slides
  {
    id: 'hotel-1',
    portal: 'hotel',
    headline: 'The Operating System for Egyptian Hospitality [NEW-v2]',
    subtext: 'AI-powered procurement, embedded finance, and ETA compliance — all in one platform.',
    ctaPrimary: { label: 'Join as Hotel', href: '/auth/register?type=hotel' },
    ctaSecondary: { label: 'Explore Platform', href: '/platform' },
    stats: [
      { value: '52 Hotels', label: 'Active Properties' },
      { value: 'EGP 86M GMV', label: 'Monthly Volume' },
      { value: '48hr SLA', label: 'Delivery Guarantee' },
    ],
    gradientFrom: '#8B1A3C',
    gradientTo: '#D4AF37',
  },
  {
    id: 'hotel-2',
    portal: 'hotel',
    headline: 'Cut Procurement Costs by 23%',
    subtext: 'Our AI engine predicts demand, benchmarks prices, and prevents stockouts before they happen.',
    ctaPrimary: { label: 'See How', href: '/savings-calculator' },
    ctaSecondary: { label: 'Watch Demo', href: '/demo' },
    stats: [
      { value: '23% Savings', label: 'Average Cost Reduction' },
      { value: '1,200+ SKUs', label: 'Catalog Depth' },
      { value: '100% Compliance', label: 'ETA Auto-Submit' },
    ],
    gradientFrom: '#8B1A3C',
    gradientTo: '#D4AF37',
  },
  {
    id: 'hotel-3',
    portal: 'hotel',
    headline: 'Embedded Finance for Hotels',
    subtext: 'Pay suppliers in 30/60/90 days through our NBFI partners. Preserve your working capital.',
    ctaPrimary: { label: 'Apply for Credit', href: '/finance/apply' },
    ctaSecondary: { label: 'Learn More', href: '/finance' },
    stats: [
      { value: '30-90 Days', label: 'Flexible Terms' },
      { value: '0.5% Origination', label: 'Low Fee' },
      { value: 'Instant Approval', label: 'Digital Decision' },
    ],
    gradientFrom: '#8B1A3C',
    gradientTo: '#D4AF37',
  },
  // Supplier Portal — 3 slides
  {
    id: 'supplier-1',
    portal: 'supplier',
    headline: "Grow with Egypt's Finest Hotels",
    subtext: 'Direct access to 52+ hotel properties. Instant payments. Verified network. Zero intermediaries.',
    ctaPrimary: { label: 'Become a Supplier', href: '/auth/register?type=supplier' },
    ctaSecondary: { label: 'How It Works', href: '/suppliers/how-it-works' },
    stats: [
      { value: '52 Hotels', label: 'Verified Buyers' },
      { value: '48hr Payment', label: 'Fast Settlement' },
      { value: '0% Commission', label: 'Direct Access' },
    ],
    gradientFrom: '#00D4AA',
    gradientTo: '#006B55',
  },
  {
    id: 'supplier-2',
    portal: 'supplier',
    headline: 'Get Paid in 48 Hours, Not 90',
    subtext: 'Choose instant payment, factoring, or credit terms. We handle the financing, you focus on quality.',
    ctaPrimary: { label: 'Join Network', href: '/auth/register?type=supplier' },
    ctaSecondary: { label: 'Pricing', href: '/suppliers/pricing' },
    stats: [
      { value: '48hr Payment', label: 'Guaranteed' },
      { value: '3 Lanes', label: 'Payment Options' },
      { value: '100% Guaranteed', label: 'Risk Covered' },
    ],
    gradientFrom: '#00D4AA',
    gradientTo: '#006B55',
  },
  {
    id: 'supplier-3',
    portal: 'supplier',
    headline: 'Your Products, Their Kitchens',
    subtext: 'List once. Sell to multiple properties. Automated reorders based on consumption patterns.',
    ctaPrimary: { label: 'Start Selling', href: '/auth/register?type=supplier' },
    ctaSecondary: { label: 'View Categories', href: '/marketplace/categories' },
    stats: [
      { value: '1,200+ SKUs', label: 'Listed Products' },
      { value: 'Auto Reorder', label: 'Smart Replenishment' },
      { value: 'Analytics', label: 'Demand Insights' },
    ],
    gradientFrom: '#00D4AA',
    gradientTo: '#006B55',
  },
  // Marketplace — 3 slides
  {
    id: 'marketplace-1',
    portal: 'marketplace',
    headline: 'Everything Your Kitchen Needs',
    subtext: '1,200+ verified SKUs. Real-time pricing. 48-hour delivery guarantee. One platform, every category.',
    ctaPrimary: { label: 'Browse Marketplace', href: '/marketplace' },
    ctaSecondary: { label: 'View Categories', href: '/marketplace/categories' },
    stats: [
      { value: '6 Categories', label: 'Product Groups' },
      { value: '68 Suppliers', label: 'Verified Partners' },
      { value: '48hr Delivery', label: 'Guaranteed' },
    ],
    gradientFrom: '#3ECF8E',
    gradientTo: '#1A5C3F',
  },
  {
    id: 'marketplace-2',
    portal: 'marketplace',
    headline: 'Compare Prices in Real Time',
    subtext: 'See cash vs credit pricing side by side. Bulk discounts applied automatically. No hidden fees.',
    ctaPrimary: { label: 'Start Browsing', href: '/marketplace' },
    ctaSecondary: { label: 'Price Guide', href: '/marketplace/pricing' },
    stats: [
      { value: 'Real-Time', label: 'Price Comparison' },
      { value: 'Bulk Discounts', label: 'Auto Applied' },
      { value: 'No Hidden Fees', label: 'Transparent' },
    ],
    gradientFrom: '#3ECF8E',
    gradientTo: '#1A5C3F',
  },
  {
    id: 'marketplace-3',
    portal: 'marketplace',
    headline: 'From Farm to Kitchen, Verified',
    subtext: 'Every supplier vetted for commercial registration, tax compliance, and delivery track record.',
    ctaPrimary: { label: 'Browse Products', href: '/marketplace' },
    ctaSecondary: { label: 'Supplier Standards', href: '/suppliers/standards' },
    stats: [
      { value: '68 Verified', label: 'Suppliers' },
      { value: 'ETA Compliant', label: 'Tax Registered' },
      { value: 'Quality Scored', label: 'Rated & Reviewed' },
    ],
    gradientFrom: '#3ECF8E',
    gradientTo: '#1A5C3F',
  },
  // Admin — 3 slides
  {
    id: 'admin-1',
    portal: 'admin',
    headline: 'Command Center for Hospitality',
    subtext: 'Real-time GMV tracking, compliance dashboards, and financial oversight across your entire network.',
    ctaPrimary: { label: 'View Dashboard', href: '/admin/dashboard' },
    ctaSecondary: { label: 'Features', href: '/admin/features' },
    stats: [
      { value: 'Real-Time', label: 'GMV Tracking' },
      { value: 'Multi-Property', label: 'Unified View' },
      { value: 'Full Control', label: 'Oversight' },
    ],
    gradientFrom: '#6C6CFF',
    gradientTo: '#2D2D99',
  },
  {
    id: 'admin-2',
    portal: 'admin',
    headline: 'Risk Management at Scale',
    subtext: 'I-Score credit monitoring, delivery SLA tracking, and anomaly detection across all transactions.',
    ctaPrimary: { label: 'Explore Analytics', href: '/admin/analytics' },
    ctaSecondary: { label: 'Security', href: '/admin/security' },
    stats: [
      { value: 'I-Score', label: 'Credit Monitoring' },
      { value: 'SLA Tracking', label: 'Delivery Oversight' },
      { value: 'Anomaly Detection', label: 'AI Alerts' },
    ],
    gradientFrom: '#6C6CFF',
    gradientTo: '#2D2D99',
  },
  {
    id: 'admin-3',
    portal: 'admin',
    headline: 'Automated Compliance, Always',
    subtext: 'ETA e-invoice auto-submission, GAFI screening, and digital agreement management.',
    ctaPrimary: { label: 'See Compliance', href: '/admin/compliance' },
    ctaSecondary: { label: 'Integrations', href: '/admin/integrations' },
    stats: [
      { value: 'ETA Auto', label: 'e-Invoice Submit' },
      { value: 'GAFI Screen', label: 'Entity Check' },
      { value: 'e-Seal Signed', label: 'Digital Agreements' },
    ],
    gradientFrom: '#6C6CFF',
    gradientTo: '#2D2D99',
  },
];

// ------------------------------------------------------------------
// 2. SUPPLIER DATA
// ------------------------------------------------------------------
export interface Supplier {
  id: string;
  name: string;
  nameAr: string;
  category: string;
  subCategory: string;
  governorate: string;
  yearsInBusiness: number;
  rating: number;
  deliveryDays: number;
  minOrder: number;
  paymentTerms: string[];
  certifications: string[];
  description: string;
  logoText: string;
  accentColor: string;
}

export const suppliers: Supplier[] = [
  {
    id: 'sup-001',
    name: 'Nile Fresh Produce',
    nameAr: 'منتجات النيل الطازجة',
    category: 'Fresh Produce',
    subCategory: 'Vegetables & Fruits',
    governorate: 'Cairo',
    yearsInBusiness: 12,
    rating: 4.7,
    deliveryDays: 1,
    minOrder: 1500,
    paymentTerms: ['COD', '7 Days', '15 Days'],
    certifications: ['ISO 22000', 'HACCP', 'Organic'],
    description: 'Premium fresh produce sourced daily from farms across the Nile Delta. Specializing in hotel-grade vegetables and fruits with same-day harvest and delivery.',
    logoText: 'NF',
    accentColor: '#2D8A3E',
  },
  {
    id: 'sup-002',
    name: 'Delta Dairy Co.',
    nameAr: 'شركة دلتا للألبان',
    category: 'Dairy & Eggs',
    subCategory: 'Dairy Products',
    governorate: 'Giza',
    yearsInBusiness: 18,
    rating: 4.8,
    deliveryDays: 1,
    minOrder: 2000,
    paymentTerms: ['COD', '7 Days', '15 Days', '30 Days'],
    certifications: ['ISO 22000', 'HACCP', 'HALAL'],
    description: 'Leading dairy processor in Greater Cairo, providing hotels with fresh milk, cheese, and yogurt produced under strict HACCP standards.',
    logoText: 'DD',
    accentColor: '#3B82F6',
  },
  {
    id: 'sup-003',
    name: 'Alexandria Seafood Hub',
    nameAr: 'محور الأسكندرية للأسماك',
    category: 'Seafood',
    subCategory: 'Fresh Fish & Shellfish',
    governorate: 'Alexandria',
    yearsInBusiness: 15,
    rating: 4.6,
    deliveryDays: 2,
    minOrder: 3000,
    paymentTerms: ['COD', '7 Days'],
    certifications: ['ISO 22000', 'HACCP', 'HALAL'],
    description: 'Direct from Mediterranean fisheries to hotel kitchens. Specializing in fresh catch daily with cold-chain logistics and custom portioning.',
    logoText: 'AS',
    accentColor: '#0EA5E9',
  },
  {
    id: 'sup-004',
    name: 'Cairo Prime Meats',
    nameAr: 'لحوم القاهرة الفاخرة',
    category: 'Meat & Poultry',
    subCategory: 'Red Meat',
    governorate: 'Cairo',
    yearsInBusiness: 20,
    rating: 4.5,
    deliveryDays: 1,
    minOrder: 2500,
    paymentTerms: ['COD', '7 Days', '15 Days'],
    certifications: ['ISO 22000', 'HACCP', 'HALAL'],
    description: 'Premium beef and lamb supplier serving five-star hotels across Cairo. Halal-certified with full traceability from farm to kitchen.',
    logoText: 'CP',
    accentColor: '#DC2626',
  },
  {
    id: 'sup-005',
    name: 'Sinai Organic Farms',
    nameAr: 'مزارع سيناء العضوية',
    category: 'Fresh Produce',
    subCategory: 'Organic Vegetables',
    governorate: 'South Sinai',
    yearsInBusiness: 8,
    rating: 4.9,
    deliveryDays: 3,
    minOrder: 2000,
    paymentTerms: ['COD', '15 Days', '30 Days'],
    certifications: ['ISO 22000', 'Organic', 'HACCP'],
    description: 'Organic produce grown in the mineral-rich soils of South Sinai. Specializing in heirloom tomatoes, herbs, and leafy greens for luxury resorts.',
    logoText: 'SO',
    accentColor: '#10B981',
  },
  {
    id: 'sup-006',
    name: 'Red Sea Fisheries',
    nameAr: 'مصائد البحر الأحمر',
    category: 'Seafood',
    subCategory: 'Fresh Fish & Shellfish',
    governorate: 'Red Sea',
    yearsInBusiness: 14,
    rating: 4.4,
    deliveryDays: 2,
    minOrder: 3500,
    paymentTerms: ['COD', '7 Days'],
    certifications: ['ISO 22000', 'HACCP'],
    description: 'Sustainable seafood from the Red Sea coast. Supplying Hurghada and Marsa Alam resorts with reef fish, squid, and shellfish.',
    logoText: 'RS',
    accentColor: '#06B6D4',
  },
  {
    id: 'sup-007',
    name: 'Luxor Grain Mills',
    nameAr: 'مطاحن الأقصر',
    category: 'Dry Goods & Grains',
    subCategory: 'Flour & Grains',
    governorate: 'Luxor',
    yearsInBusiness: 25,
    rating: 4.3,
    deliveryDays: 3,
    minOrder: 1500,
    paymentTerms: ['COD', '15 Days', '30 Days', '60 Days'],
    certifications: ['ISO 22000', 'HACCP'],
    description: 'One of Upper Egypt\'s oldest grain mills, producing premium flour, rice, and pasta for hospitality kitchens throughout the Nile Valley.',
    logoText: 'LG',
    accentColor: '#D97706',
  },
  {
    id: 'sup-008',
    name: 'Aswan Spice Traders',
    nameAr: 'تجار التوابل بأسوان',
    category: 'Dry Goods & Grains',
    subCategory: 'Spices & Seasonings',
    governorate: 'Aswan',
    yearsInBusiness: 22,
    rating: 4.6,
    deliveryDays: 4,
    minOrder: 1000,
    paymentTerms: ['COD', '15 Days', '30 Days'],
    certifications: ['ISO 22000', 'HACCP', 'HALAL'],
    description: 'Authentic Nubian spices and blends sourced from traditional growers. Custom spice mixes and bulk seasonings for hotel kitchens.',
    logoText: 'AS',
    accentColor: '#B45309',
  },
  {
    id: 'sup-009',
    name: 'Damietta Poultry',
    nameAr: 'دواجن دمياط',
    category: 'Meat & Poultry',
    subCategory: 'Poultry',
    governorate: 'Damietta',
    yearsInBusiness: 16,
    rating: 4.5,
    deliveryDays: 2,
    minOrder: 2000,
    paymentTerms: ['COD', '7 Days', '15 Days'],
    certifications: ['ISO 22000', 'HACCP', 'HALAL'],
    description: 'Fresh and frozen poultry products from the Delta region. Whole birds, cuts, and processed items with consistent quality and sizing.',
    logoText: 'DP',
    accentColor: '#EF4444',
  },
  {
    id: 'sup-010',
    name: 'Port Said Beverages',
    nameAr: 'مشروبات بورسعيد',
    category: 'Beverages',
    subCategory: 'Soft Drinks & Juices',
    governorate: 'Port Said',
    yearsInBusiness: 10,
    rating: 4.2,
    deliveryDays: 2,
    minOrder: 1500,
    paymentTerms: ['COD', '7 Days', '15 Days', '30 Days'],
    certifications: ['ISO 22000', 'HACCP'],
    description: 'Beverage distributor covering the Canal Zone. Supplying hotels with juices, mineral water, and soft drinks from leading Egyptian brands.',
    logoText: 'PB',
    accentColor: '#8B5CF6',
  },
  {
    id: 'sup-011',
    name: 'Kafr El-Sheikh Vegetables',
    nameAr: 'خضروات كفر الشيخ',
    category: 'Fresh Produce',
    subCategory: 'Vegetables & Fruits',
    governorate: 'Kafr El-Sheikh',
    yearsInBusiness: 14,
    rating: 4.4,
    deliveryDays: 2,
    minOrder: 1200,
    paymentTerms: ['COD', '7 Days', '15 Days'],
    certifications: ['ISO 22000', 'HACCP'],
    description: 'Delta-grown vegetables harvested at peak ripeness. Reliable supply of cucumbers, tomatoes, peppers, and leafy greens for Cairo and Alexandria hotels.',
    logoText: 'KV',
    accentColor: '#22C55E',
  },
  {
    id: 'sup-012',
    name: 'Giza Cleaning Solutions',
    nameAr: 'حلول التنظيف بالجيزة',
    category: 'Cleaning & Hygiene',
    subCategory: 'Cleaning Chemicals',
    governorate: 'Giza',
    yearsInBusiness: 9,
    rating: 4.3,
    deliveryDays: 1,
    minOrder: 1000,
    paymentTerms: ['COD', '7 Days', '15 Days', '30 Days'],
    certifications: ['ISO 22000', 'HACCP'],
    description: 'Industrial-grade cleaning chemicals and hygiene products manufactured in Giza. Floor cleaners, disinfectants, and sanitizers for hotel operations.',
    logoText: 'GC',
    accentColor: '#6366F1',
  },
  {
    id: 'sup-013',
    name: 'Cairo Kitchen Equipment',
    nameAr: 'معدات مطابخ القاهرة',
    category: 'Kitchen Equipment',
    subCategory: 'Cookware & Tools',
    governorate: 'Cairo',
    yearsInBusiness: 11,
    rating: 4.1,
    deliveryDays: 3,
    minOrder: 5000,
    paymentTerms: ['COD', '15 Days', '30 Days', '60 Days'],
    certifications: ['ISO 22000', 'HACCP'],
    description: 'Commercial kitchen equipment and smallwares for hotels. Pots, pans, knives, and utensils from European and local manufacturers.',
    logoText: 'CK',
    accentColor: '#64748B',
  },
  {
    id: 'sup-014',
    name: 'Alexandria Dairy Farms',
    nameAr: 'مزارع الإسكندرية للألبان',
    category: 'Dairy & Eggs',
    subCategory: 'Dairy Products',
    governorate: 'Alexandria',
    yearsInBusiness: 19,
    rating: 4.7,
    deliveryDays: 1,
    minOrder: 1800,
    paymentTerms: ['COD', '7 Days', '15 Days', '30 Days'],
    certifications: ['ISO 22000', 'HACCP', 'HALAL', 'Organic'],
    description: 'Family-run dairy farm in Alexandria\'s agricultural belt. Farm-fresh milk, artisanal cheese, and organic yogurt for boutique and luxury hotels.',
    logoText: 'AD',
    accentColor: '#3B82F6',
  },
  {
    id: 'sup-015',
    name: 'Red Sea Produce',
    nameAr: 'منتجات البحر الأحمر',
    category: 'Fresh Produce',
    subCategory: 'Vegetables & Fruits',
    governorate: 'Red Sea',
    yearsInBusiness: 7,
    rating: 4.5,
    deliveryDays: 2,
    minOrder: 2000,
    paymentTerms: ['COD', '15 Days', '30 Days'],
    certifications: ['ISO 22000', 'HACCP'],
    description: 'Tropical and subtropical produce for Red Sea resorts. Fresh herbs, salad greens, and exotic fruits grown in controlled greenhouse environments.',
    logoText: 'RP',
    accentColor: '#14B8A6',
  },
  {
    id: 'sup-016',
    name: 'Sinai Beverage Co.',
    nameAr: 'شركة سيناء للمشروبات',
    category: 'Beverages',
    subCategory: 'Soft Drinks & Juices',
    governorate: 'South Sinai',
    yearsInBusiness: 6,
    rating: 4.3,
    deliveryDays: 3,
    minOrder: 1500,
    paymentTerms: ['COD', '7 Days', '15 Days'],
    certifications: ['ISO 22000', 'HACCP', 'HALAL'],
    description: 'Beverage bottling and distribution for Sinai resorts. Specialized in large-format juices, water, and traditional Egyptian drinks.',
    logoText: 'SB',
    accentColor: '#A855F7',
  },
  {
    id: 'sup-017',
    name: 'Luxor Meat Processing',
    nameAr: 'معالجة اللحوم بالأقصر',
    category: 'Meat & Poultry',
    subCategory: 'Processed Meats',
    governorate: 'Luxor',
    yearsInBusiness: 13,
    rating: 4.4,
    deliveryDays: 3,
    minOrder: 2500,
    paymentTerms: ['COD', '7 Days', '15 Days', '30 Days'],
    certifications: ['ISO 22000', 'HACCP', 'HALAL'],
    description: 'Upper Egypt\'s premier meat processor. Custom cuts, marinated meats, and hotel-ready portions with full Halal certification.',
    logoText: 'LM',
    accentColor: '#DC2626',
  },
  {
    id: 'sup-018',
    name: 'Aswan Fresh Foods',
    nameAr: 'أطعمة أسوان الطازجة',
    category: 'Fresh Produce',
    subCategory: 'Vegetables & Fruits',
    governorate: 'Aswan',
    yearsInBusiness: 11,
    rating: 4.6,
    deliveryDays: 4,
    minOrder: 1500,
    paymentTerms: ['COD', '15 Days', '30 Days'],
    certifications: ['ISO 22000', 'HACCP', 'Organic'],
    description: 'Nile-grown produce from Aswan\'s fertile banks. Mangoes, dates, bananas, and seasonal vegetables for luxury Nile cruise operators and hotels.',
    logoText: 'AF',
    accentColor: '#F59E0B',
  },
  {
    id: 'sup-019',
    name: 'Cairo Beverage Group',
    nameAr: 'مجموعة مشروبات القاهرة',
    category: 'Beverages',
    subCategory: 'Soft Drinks & Juices',
    governorate: 'Cairo',
    yearsInBusiness: 17,
    rating: 4.5,
    deliveryDays: 1,
    minOrder: 2000,
    paymentTerms: ['COD', '7 Days', '15 Days', '30 Days', '60 Days'],
    certifications: ['ISO 22000', 'HACCP', 'HALAL'],
    description: 'Major beverage distributor in Greater Cairo. Exclusive distribution agreements with international and local juice, water, and soft drink brands.',
    logoText: 'CB',
    accentColor: '#7C3AED',
  },
  {
    id: 'sup-020',
    name: 'Alexandria Cleaning Pro',
    nameAr: 'ألكسندريا كلينينج برو',
    category: 'Cleaning & Hygiene',
    subCategory: 'Disposable Supplies',
    governorate: 'Alexandria',
    yearsInBusiness: 8,
    rating: 4.2,
    deliveryDays: 2,
    minOrder: 1200,
    paymentTerms: ['COD', '7 Days', '15 Days', '30 Days'],
    certifications: ['ISO 22000', 'HACCP'],
    description: 'Hotel hygiene and disposable supplies specialist. Paper products, garbage bags, and cleaning accessories for Alexandria\'s hotel market.',
    logoText: 'AC',
    accentColor: '#4F46E5',
  },
  {
    id: 'sup-021',
    name: 'Giza Poultry Farms',
    nameAr: 'مزارع دواجن الجيزة',
    category: 'Meat & Poultry',
    subCategory: 'Poultry',
    governorate: 'Giza',
    yearsInBusiness: 15,
    rating: 4.6,
    deliveryDays: 1,
    minOrder: 2000,
    paymentTerms: ['COD', '7 Days', '15 Days'],
    certifications: ['ISO 22000', 'HACCP', 'HALAL'],
    description: 'Large-scale poultry farm and processing facility in Giza. Fresh and frozen chicken products with consistent sizing and competitive pricing.',
    logoText: 'GP',
    accentColor: '#E11D48',
  },
  {
    id: 'sup-022',
    name: 'Damietta Dry Goods',
    nameAr: 'البضائع الجافة بدمياط',
    category: 'Dry Goods & Grains',
    subCategory: 'Pasta & Rice',
    governorate: 'Damietta',
    yearsInBusiness: 21,
    rating: 4.4,
    deliveryDays: 2,
    minOrder: 1500,
    paymentTerms: ['COD', '15 Days', '30 Days'],
    certifications: ['ISO 22000', 'HACCP', 'HALAL'],
    description: 'Damietta-based dry goods specialist. Premium pasta, rice, lentils, and cooking oils packaged for commercial kitchen use.',
    logoText: 'DD',
    accentColor: '#D97706',
  },
  {
    id: 'sup-023',
    name: 'Port Said Equipment',
    nameAr: 'معدات بورسعيد',
    category: 'Kitchen Equipment',
    subCategory: 'Appliances & Machines',
    governorate: 'Port Said',
    yearsInBusiness: 5,
    rating: 4.0,
    deliveryDays: 3,
    minOrder: 5000,
    paymentTerms: ['COD', '15 Days', '30 Days', '60 Days'],
    certifications: ['ISO 22000', 'HACCP'],
    description: 'Commercial kitchen appliances and equipment for hotels in the Canal Zone. Ovens, mixers, refrigeration, and food prep machines.',
    logoText: 'PE',
    accentColor: '#475569',
  },
  {
    id: 'sup-024',
    name: 'Kafr El-Sheikh Dairy',
    nameAr: 'ألبان كفر الشيخ',
    category: 'Dairy & Eggs',
    subCategory: 'Dairy Products',
    governorate: 'Kafr El-Sheikh',
    yearsInBusiness: 12,
    rating: 4.5,
    deliveryDays: 2,
    minOrder: 1500,
    paymentTerms: ['COD', '7 Days', '15 Days', '30 Days'],
    certifications: ['ISO 22000', 'HACCP', 'HALAL'],
    description: 'Delta dairy cooperative producing fresh milk, cheese, and butter. Reliable supply chain for hotels across the northern Delta region.',
    logoText: 'KD',
    accentColor: '#2563EB',
  },
];

// ------------------------------------------------------------------
// 3. PRODUCT DATA
// ------------------------------------------------------------------
export interface Product {
  id: string;
  name: string;
  nameAr: string;
  category: string;
  subCategory: string;
  supplierId: string;
  unit: string;
  basePrice: number;
  creditPrice: number;
  moq: number;
  sku: string;
  inStock: boolean;
  leadTime: number;
  description: string;
}

export const products: Product[] = [
  // --- Fresh Produce (8 products) ---
  {
    id: 'prod-001',
    name: 'Tomatoes',
    nameAr: 'طماطم',
    category: 'Fresh Produce',
    subCategory: 'Vegetables',
    supplierId: 'sup-001',
    unit: 'kg',
    basePrice: 12,
    creditPrice: 12.72,
    moq: 10,
    sku: 'HV-FP-001',
    inStock: true,
    leadTime: 1,
    description: 'Vine-ripened tomatoes, hotel-grade size and color consistency. Ideal for salads, sauces, and garnishes.',
  },
  {
    id: 'prod-002',
    name: 'Cucumbers',
    nameAr: 'خيار',
    category: 'Fresh Produce',
    subCategory: 'Vegetables',
    supplierId: 'sup-001',
    unit: 'kg',
    basePrice: 8,
    creditPrice: 8.56,
    moq: 10,
    sku: 'HV-FP-002',
    inStock: true,
    leadTime: 1,
    description: 'Crisp, fresh cucumbers with uniform length. Perfect for salads, cold buffets, and pickling.',
  },
  {
    id: 'prod-003',
    name: 'Bell Peppers',
    nameAr: 'فلفل ألوان',
    category: 'Fresh Produce',
    subCategory: 'Vegetables',
    supplierId: 'sup-011',
    unit: 'kg',
    basePrice: 18,
    creditPrice: 19.08,
    moq: 5,
    sku: 'HV-FP-003',
    inStock: true,
    leadTime: 2,
    description: 'Mixed color bell peppers — red, yellow, and green. Firm texture, vibrant color for plating and cooking.',
  },
  {
    id: 'prod-004',
    name: 'Lettuce',
    nameAr: 'خس',
    category: 'Fresh Produce',
    subCategory: 'Leafy Greens',
    supplierId: 'sup-005',
    unit: 'kg',
    basePrice: 10,
    creditPrice: 10.70,
    moq: 5,
    sku: 'HV-FP-004',
    inStock: true,
    leadTime: 3,
    description: 'Organic iceberg and romaine lettuce. Crisp leaves, pre-cooled, ready for salad bars and room service.',
  },
  {
    id: 'prod-005',
    name: 'Red Onions',
    nameAr: 'بصل أحمر',
    category: 'Fresh Produce',
    subCategory: 'Vegetables',
    supplierId: 'sup-011',
    unit: 'kg',
    basePrice: 9,
    creditPrice: 9.63,
    moq: 10,
    sku: 'HV-FP-005',
    inStock: true,
    leadTime: 2,
    description: 'Medium-sized red onions with firm skin. Ideal for grilling, pickling, and raw preparations.',
  },
  {
    id: 'prod-006',
    name: 'Garlic',
    nameAr: 'ثوم',
    category: 'Fresh Produce',
    subCategory: 'Vegetables',
    supplierId: 'sup-018',
    unit: 'kg',
    basePrice: 22,
    creditPrice: 23.54,
    moq: 5,
    sku: 'HV-FP-006',
    inStock: true,
    leadTime: 4,
    description: 'Large-clove garlic from Aswan. Strong aroma and flavor, preferred by chefs for sauces and marinades.',
  },
  {
    id: 'prod-007',
    name: 'Lemons',
    nameAr: 'ليمون',
    category: 'Fresh Produce',
    subCategory: 'Citrus',
    supplierId: 'sup-018',
    unit: 'kg',
    basePrice: 14,
    creditPrice: 14.98,
    moq: 5,
    sku: 'HV-FP-007',
    inStock: true,
    leadTime: 4,
    description: 'Juicy Egyptian lemons with thin skin and high juice content. Essential for beverages, dressings, and seafood.',
  },
  {
    id: 'prod-008',
    name: 'Mixed Herbs',
    nameAr: 'أعشاب مشكلة',
    category: 'Fresh Produce',
    subCategory: 'Herbs',
    supplierId: 'sup-005',
    unit: 'kg',
    basePrice: 35,
    creditPrice: 37.10,
    moq: 2,
    sku: 'HV-FP-008',
    inStock: true,
    leadTime: 3,
    description: 'Fresh basil, parsley, coriander, dill, and mint. Harvested daily, pre-sorted for hotel kitchen use.',
  },
  // --- Dairy & Eggs (8 products) ---
  {
    id: 'prod-009',
    name: 'Full Cream Milk 1L',
    nameAr: 'حليب كامل الدسم 1 لتر',
    category: 'Dairy & Eggs',
    subCategory: 'Milk',
    supplierId: 'sup-002',
    unit: 'liter',
    basePrice: 28,
    creditPrice: 29.68,
    moq: 24,
    sku: 'HV-DE-001',
    inStock: true,
    leadTime: 1,
    description: 'Pasteurized full cream milk in 1-liter cartons. Long shelf life, consistent fat content for coffee and cooking.',
  },
  {
    id: 'prod-010',
    name: 'Labneh 500g',
    nameAr: 'لبنة 500 جرام',
    category: 'Dairy & Eggs',
    subCategory: 'Yogurt & Labneh',
    supplierId: 'sup-002',
    unit: 'unit',
    basePrice: 32,
    creditPrice: 33.92,
    moq: 12,
    sku: 'HV-DE-002',
    inStock: true,
    leadTime: 1,
    description: 'Creamy strained yogurt (labneh) in 500g tubs. Perfect for breakfast buffets and mezze platters.',
  },
  {
    id: 'prod-011',
    name: 'White Cheese 1kg',
    nameAr: 'جبنة بيضاء 1 كجم',
    category: 'Dairy & Eggs',
    subCategory: 'Cheese',
    supplierId: 'sup-014',
    unit: 'kg',
    basePrice: 85,
    creditPrice: 90.10,
    moq: 5,
    sku: 'HV-DE-003',
    inStock: true,
    leadTime: 1,
    description: 'Traditional Egyptian white cheese (domiati) in brine. Creamy texture, mild saltiness, ideal for breakfast service.',
  },
  {
    id: 'prod-012',
    name: 'Cheddar Cheese 1kg',
    nameAr: 'جبنة شيدر 1 كجم',
    category: 'Dairy & Eggs',
    subCategory: 'Cheese',
    supplierId: 'sup-014',
    unit: 'kg',
    basePrice: 120,
    creditPrice: 127.20,
    moq: 5,
    sku: 'HV-DE-004',
    inStock: true,
    leadTime: 1,
    description: 'Aged cheddar cheese block, sharp flavor. Excellent for sandwiches, burgers, and cheese boards.',
  },
  {
    id: 'prod-013',
    name: 'Unsalted Butter 500g',
    nameAr: 'زبدة غير مملحة 500 جرام',
    category: 'Dairy & Eggs',
    subCategory: 'Butter & Ghee',
    supplierId: 'sup-002',
    unit: 'unit',
    basePrice: 55,
    creditPrice: 58.30,
    moq: 10,
    sku: 'HV-DE-005',
    inStock: true,
    leadTime: 1,
    description: 'Premium unsalted butter for baking and cooking. 82% fat content, consistent quality for pastry kitchens.',
  },
  {
    id: 'prod-014',
    name: 'Greek Yogurt 1kg',
    nameAr: 'زبادي يوناني 1 كجم',
    category: 'Dairy & Eggs',
    subCategory: 'Yogurt & Labneh',
    supplierId: 'sup-024',
    unit: 'kg',
    basePrice: 48,
    creditPrice: 50.88,
    moq: 6,
    sku: 'HV-DE-006',
    inStock: true,
    leadTime: 2,
    description: 'Thick Greek yogurt, high protein, low fat. Popular for breakfast buffets, smoothies, and healthy menu options.',
  },
  {
    id: 'prod-015',
    name: 'Eggs (30pc tray)',
    nameAr: 'بيض (علبة 30 بيضة)',
    category: 'Dairy & Eggs',
    subCategory: 'Eggs',
    supplierId: 'sup-021',
    unit: 'tray',
    basePrice: 95,
    creditPrice: 100.70,
    moq: 10,
    sku: 'HV-DE-007',
    inStock: true,
    leadTime: 1,
    description: 'Large white eggs, grade A, 30 per tray. Consistent size and shell quality for baking and breakfast service.',
  },
  {
    id: 'prod-016',
    name: 'Cooking Cream 1L',
    nameAr: 'كريمة طهي 1 لتر',
    category: 'Dairy & Eggs',
    subCategory: 'Cream',
    supplierId: 'sup-024',
    unit: 'liter',
    basePrice: 42,
    creditPrice: 44.52,
    moq: 12,
    sku: 'HV-DE-008',
    inStock: true,
    leadTime: 2,
    description: 'Heavy cooking cream with 35% fat content. Stable under heat, ideal for sauces, soups, and pasta dishes.',
  },
  // --- Meat & Poultry (8 products) ---
  {
    id: 'prod-017',
    name: 'Chicken Breast',
    nameAr: 'صدر دجاج',
    category: 'Meat & Poultry',
    subCategory: 'Poultry',
    supplierId: 'sup-021',
    unit: 'kg',
    basePrice: 95,
    creditPrice: 100.70,
    moq: 10,
    sku: 'HV-MP-001',
    inStock: true,
    leadTime: 1,
    description: 'Skinless, boneless chicken breast fillets. Uniform size, trimmed, and individually quick frozen or fresh.',
  },
  {
    id: 'prod-018',
    name: 'Chicken Wings',
    nameAr: 'أجنحة دجاج',
    category: 'Meat & Poultry',
    subCategory: 'Poultry',
    supplierId: 'sup-009',
    unit: 'kg',
    basePrice: 72,
    creditPrice: 76.32,
    moq: 10,
    sku: 'HV-MP-002',
    inStock: true,
    leadTime: 2,
    description: 'Whole chicken wings, mid-joint and drumette separated. Ideal for frying, grilling, and buffet stations.',
  },
  {
    id: 'prod-019',
    name: 'Beef Fillet',
    nameAr: 'فيليه بقري',
    category: 'Meat & Poultry',
    subCategory: 'Beef',
    supplierId: 'sup-004',
    unit: 'kg',
    basePrice: 450,
    creditPrice: 477.00,
    moq: 3,
    sku: 'HV-MP-003',
    inStock: true,
    leadTime: 1,
    description: 'Premium beef tenderloin, trimmed and ready for portioning. Tender, lean, perfect for fine dining menus.',
  },
  {
    id: 'prod-020',
    name: 'Lamb Chops',
    nameAr: 'ريش ضاني',
    category: 'Meat & Poultry',
    subCategory: 'Lamb',
    supplierId: 'sup-004',
    unit: 'kg',
    basePrice: 380,
    creditPrice: 402.80,
    moq: 3,
    sku: 'HV-MP-004',
    inStock: true,
    leadTime: 1,
    description: 'Frenched lamb chops, consistent thickness. Rich flavor, ideal for grill and roast applications.',
  },
  {
    id: 'prod-021',
    name: 'Minced Beef',
    nameAr: 'لحم مفروم',
    category: 'Meat & Poultry',
    subCategory: 'Beef',
    supplierId: 'sup-017',
    unit: 'kg',
    basePrice: 180,
    creditPrice: 190.80,
    moq: 5,
    sku: 'HV-MP-005',
    inStock: true,
    leadTime: 3,
    description: 'Lean minced beef, 85/15 lean-to-fat ratio. Freshly ground daily, vacuum packed for extended shelf life.',
  },
  {
    id: 'prod-022',
    name: 'Chicken Liver',
    nameAr: 'كبدة دجاج',
    category: 'Meat & Poultry',
    subCategory: 'Poultry Offal',
    supplierId: 'sup-009',
    unit: 'kg',
    basePrice: 55,
    creditPrice: 58.30,
    moq: 5,
    sku: 'HV-MP-006',
    inStock: true,
    leadTime: 2,
    description: 'Fresh chicken liver, cleaned and packed. Popular for Egyptian and Mediterranean breakfast and dinner menus.',
  },
  {
    id: 'prod-023',
    name: 'Turkey Breast',
    nameAr: 'صدر ديك رومي',
    category: 'Meat & Poultry',
    subCategory: 'Poultry',
    supplierId: 'sup-017',
    unit: 'kg',
    basePrice: 145,
    creditPrice: 153.70,
    moq: 5,
    sku: 'HV-MP-007',
    inStock: true,
    leadTime: 3,
    description: 'Boneless turkey breast, skin-on or skinless options. Lean protein for health-conscious menus and deli counters.',
  },
  {
    id: 'prod-024',
    name: 'Duck Breast',
    nameAr: 'صدر بط',
    category: 'Meat & Poultry',
    subCategory: 'Poultry',
    supplierId: 'sup-004',
    unit: 'kg',
    basePrice: 290,
    creditPrice: 307.40,
    moq: 3,
    sku: 'HV-MP-008',
    inStock: true,
    leadTime: 1,
    description: 'Magret duck breast, skin-on, scored. Rich flavor and tender meat for upscale dining and special events.',
  },
  // --- Dry Goods & Grains (8 products) ---
  {
    id: 'prod-025',
    name: 'Basmati Rice 5kg',
    nameAr: 'أرز بسمتي 5 كجم',
    category: 'Dry Goods & Grains',
    subCategory: 'Rice',
    supplierId: 'sup-007',
    unit: 'bag',
    basePrice: 95,
    creditPrice: 100.70,
    moq: 10,
    sku: 'HV-DG-001',
    inStock: true,
    leadTime: 3,
    description: 'Premium aged basmati rice, long grain, non-sticky. Aromatic and fluffy when cooked. Ideal for biryani and pilaf.',
  },
  {
    id: 'prod-026',
    name: 'Pasta Penne 5kg',
    nameAr: 'مكرونة بيني 5 كجم',
    category: 'Dry Goods & Grains',
    subCategory: 'Pasta',
    supplierId: 'sup-022',
    unit: 'bag',
    basePrice: 85,
    creditPrice: 90.10,
    moq: 10,
    sku: 'HV-DG-002',
    inStock: true,
    leadTime: 2,
    description: 'Durum wheat penne pasta, holds sauce well. Consistent cooking quality, al dente texture every time.',
  },
  {
    id: 'prod-027',
    name: 'All Purpose Flour 5kg',
    nameAr: 'دقيق متعدد الاستخدامات 5 كجم',
    category: 'Dry Goods & Grains',
    subCategory: 'Flour',
    supplierId: 'sup-007',
    unit: 'bag',
    basePrice: 55,
    creditPrice: 58.30,
    moq: 10,
    sku: 'HV-DG-003',
    inStock: true,
    leadTime: 3,
    description: 'High-quality all-purpose wheat flour. Versatile for baking bread, pastries, and thickening sauces.',
  },
  {
    id: 'prod-028',
    name: 'White Sugar 5kg',
    nameAr: 'سكر أبيض 5 كجم',
    category: 'Dry Goods & Grains',
    subCategory: 'Sugar',
    supplierId: 'sup-022',
    unit: 'bag',
    basePrice: 45,
    creditPrice: 47.70,
    moq: 10,
    sku: 'HV-DG-004',
    inStock: true,
    leadTime: 2,
    description: 'Refined white crystalline sugar. Fine granules dissolve quickly. Essential for baking, beverages, and dessert preparation.',
  },
  {
    id: 'prod-029',
    name: 'Sunflower Oil 5L',
    nameAr: 'زيت عباد الشمس 5 لتر',
    category: 'Dry Goods & Grains',
    subCategory: 'Cooking Oil',
    supplierId: 'sup-022',
    unit: 'unit',
    basePrice: 120,
    creditPrice: 127.20,
    moq: 6,
    sku: 'HV-DG-005',
    inStock: true,
    leadTime: 2,
    description: 'High-oleic sunflower oil in 5-liter jerrycan. High smoke point, neutral flavor. Ideal for frying and general cooking.',
  },
  {
    id: 'prod-030',
    name: 'Red Lentils 2kg',
    nameAr: 'عدس أحمر 2 كجم',
    category: 'Dry Goods & Grains',
    subCategory: 'Legumes',
    supplierId: 'sup-007',
    unit: 'bag',
    basePrice: 38,
    creditPrice: 40.28,
    moq: 10,
    sku: 'HV-DG-006',
    inStock: true,
    leadTime: 3,
    description: 'Split red lentils, quick-cooking. Popular for soups, stews, and Egyptian lentil dishes. High protein and fiber.',
  },
  {
    id: 'prod-031',
    name: 'Chickpeas 2kg',
    nameAr: 'حمص 2 كجم',
    category: 'Dry Goods & Grains',
    subCategory: 'Legumes',
    supplierId: 'sup-008',
    unit: 'bag',
    basePrice: 32,
    creditPrice: 33.92,
    moq: 10,
    sku: 'HV-DG-007',
    inStock: true,
    leadTime: 4,
    description: 'Dried chickpeas, uniform size. Essential for hummus, falafel, and Mediterranean salads. Soak overnight for best results.',
  },
  {
    id: 'prod-032',
    name: 'Tomato Paste 4kg',
    nameAr: 'معجون طماطم 4 كجم',
    category: 'Dry Goods & Grains',
    subCategory: 'Canned & Paste',
    supplierId: 'sup-008',
    unit: 'unit',
    basePrice: 65,
    creditPrice: 68.90,
    moq: 6,
    sku: 'HV-DG-008',
    inStock: true,
    leadTime: 4,
    description: 'Concentrated tomato paste in large commercial tin. Rich red color, thick consistency for sauces, stews, and bases.',
  },
  // --- Beverages (8 products) ---
  {
    id: 'prod-033',
    name: 'Orange Juice 1L',
    nameAr: 'عصير برتقال 1 لتر',
    category: 'Beverages',
    subCategory: 'Juices',
    supplierId: 'sup-019',
    unit: 'liter',
    basePrice: 22,
    creditPrice: 23.32,
    moq: 12,
    sku: 'HV-BV-001',
    inStock: true,
    leadTime: 1,
    description: '100% pure orange juice, not from concentrate. Fresh taste, no added sugar. Popular for breakfast buffets and room service.',
  },
  {
    id: 'prod-034',
    name: 'Mango Juice 1L',
    nameAr: 'عصير مانجو 1 لتر',
    category: 'Beverages',
    subCategory: 'Juices',
    supplierId: 'sup-019',
    unit: 'liter',
    basePrice: 24,
    creditPrice: 25.44,
    moq: 12,
    sku: 'HV-BV-002',
    inStock: true,
    leadTime: 1,
    description: 'Premium Egyptian mango juice. Thick, aromatic, and naturally sweet. A guest favorite at breakfast and pool bars.',
  },
  {
    id: 'prod-035',
    name: 'Mineral Water (12x500ml)',
    nameAr: 'مياه معدنية (12×500 مل)',
    category: 'Beverages',
    subCategory: 'Water',
    supplierId: 'sup-010',
    unit: 'case',
    basePrice: 28,
    creditPrice: 29.68,
    moq: 10,
    sku: 'HV-BV-003',
    inStock: true,
    leadTime: 2,
    description: 'Natural mineral water, 12 bottles of 500ml per case. Essential for minibars, meeting rooms, and restaurant service.',
  },
  {
    id: 'prod-036',
    name: 'Sparkling Water (12x500ml)',
    nameAr: 'مياه غازية (12×500 مل)',
    category: 'Beverages',
    subCategory: 'Water',
    supplierId: 'sup-010',
    unit: 'case',
    basePrice: 32,
    creditPrice: 33.92,
    moq: 10,
    sku: 'HV-BV-004',
    inStock: true,
    leadTime: 2,
    description: 'Carbonated mineral water, 12 bottles of 500ml per case. Popular for mixology and upscale dining experiences.',
  },
  {
    id: 'prod-037',
    name: 'Black Tea 100bags',
    nameAr: 'شاي أسود 100 كيس',
    category: 'Beverages',
    subCategory: 'Tea',
    supplierId: 'sup-019',
    unit: 'box',
    basePrice: 18,
    creditPrice: 19.08,
    moq: 12,
    sku: 'HV-BV-005',
    inStock: true,
    leadTime: 1,
    description: 'Premium black tea bags, 100 per box. Strong brew, consistent flavor. Essential for room service and restaurant service.',
  },
  {
    id: 'prod-038',
    name: 'Coffee Beans 1kg',
    nameAr: 'حبوب قهوة 1 كجم',
    category: 'Beverages',
    subCategory: 'Coffee',
    supplierId: 'sup-016',
    unit: 'kg',
    basePrice: 95,
    creditPrice: 100.70,
    moq: 5,
    sku: 'HV-BV-006',
    inStock: true,
    leadTime: 3,
    description: 'Medium roast arabica coffee beans. Rich aroma with chocolate and nutty notes. Ideal for espresso machines and drip brewers.',
  },
  {
    id: 'prod-039',
    name: 'Hot Chocolate 1kg',
    nameAr: 'شوكولاتة ساخنة 1 كجم',
    category: 'Beverages',
    subCategory: 'Hot Drinks',
    supplierId: 'sup-016',
    unit: 'kg',
    basePrice: 42,
    creditPrice: 44.52,
    moq: 6,
    sku: 'HV-BV-007',
    inStock: true,
    leadTime: 3,
    description: 'Rich hot chocolate powder. Creamy texture when prepared with milk. Popular for kids menus and winter beverage programs.',
  },
  {
    id: 'prod-040',
    name: 'Cola (12x330ml)',
    nameAr: 'كولا (12×330 مل)',
    category: 'Beverages',
    subCategory: 'Soft Drinks',
    supplierId: 'sup-019',
    unit: 'case',
    basePrice: 48,
    creditPrice: 50.88,
    moq: 10,
    sku: 'HV-BV-008',
    inStock: true,
    leadTime: 1,
    description: 'Classic cola soft drink, 12 cans of 330ml per case. Staple for minibars, bars, and room service across all properties.',
  },
  // --- Cleaning & Hygiene (8 products) ---
  {
    id: 'prod-041',
    name: 'Floor Cleaner 5L',
    nameAr: 'منظف أرضيات 5 لتر',
    category: 'Cleaning & Hygiene',
    subCategory: 'Cleaners',
    supplierId: 'sup-012',
    unit: 'unit',
    basePrice: 55,
    creditPrice: 58.30,
    moq: 6,
    sku: 'HV-CH-001',
    inStock: true,
    leadTime: 1,
    description: 'Industrial-strength floor cleaner, pine scented. Effective on tile, marble, and vinyl surfaces. 5-liter concentrate.',
  },
  {
    id: 'prod-042',
    name: 'Dish Soap 5L',
    nameAr: 'صابون أطباق 5 لتر',
    category: 'Cleaning & Hygiene',
    subCategory: 'Cleaners',
    supplierId: 'sup-012',
    unit: 'unit',
    basePrice: 48,
    creditPrice: 50.88,
    moq: 6,
    sku: 'HV-CH-002',
    inStock: true,
    leadTime: 1,
    description: 'High-foam dishwashing liquid for commercial kitchens. Cuts grease on pots, pans, and plates. 5-liter refill.',
  },
  {
    id: 'prod-043',
    name: 'Hand Soap 5L',
    nameAr: 'صابون يدين 5 لتر',
    category: 'Cleaning & Hygiene',
    subCategory: 'Cleaners',
    supplierId: 'sup-012',
    unit: 'unit',
    basePrice: 42,
    creditPrice: 44.52,
    moq: 6,
    sku: 'HV-CH-003',
    inStock: true,
    leadTime: 1,
    description: 'Antibacterial liquid hand soap, mild on skin. For kitchen and restroom dispensers. 5-liter refill container.',
  },
  {
    id: 'prod-044',
    name: 'Garbage Bags (100pc)',
    nameAr: 'أكياس قمامة (100 قطعة)',
    category: 'Cleaning & Hygiene',
    subCategory: 'Disposables',
    supplierId: 'sup-020',
    unit: 'roll',
    basePrice: 85,
    creditPrice: 90.10,
    moq: 5,
    sku: 'HV-CH-004',
    inStock: true,
    leadTime: 2,
    description: 'Heavy-duty black garbage bags, 100 per roll. Tear-resistant, suitable for wet and dry waste in kitchens and housekeeping.',
  },
  {
    id: 'prod-045',
    name: 'Paper Towels (12 rolls)',
    nameAr: 'مناشف ورقية (12 رول)',
    category: 'Cleaning & Hygiene',
    subCategory: 'Paper Products',
    supplierId: 'sup-020',
    unit: 'case',
    basePrice: 95,
    creditPrice: 100.70,
    moq: 5,
    sku: 'HV-CH-005',
    inStock: true,
    leadTime: 2,
    description: 'Multi-fold paper towels, 12 rolls per case. High absorbency for kitchen and restroom dispensers.',
  },
  {
    id: 'prod-046',
    name: 'Toilet Paper (24 rolls)',
    nameAr: 'ورق تواليت (24 رول)',
    category: 'Cleaning & Hygiene',
    subCategory: 'Paper Products',
    supplierId: 'sup-020',
    unit: 'case',
    basePrice: 120,
    creditPrice: 127.20,
    moq: 5,
    sku: 'HV-CH-006',
    inStock: true,
    leadTime: 2,
    description: '2-ply toilet tissue, 24 rolls per case. Soft yet strong. Standard size for commercial restroom dispensers.',
  },
  {
    id: 'prod-047',
    name: 'Surface Disinfectant 5L',
    nameAr: 'مطهر أسطح 5 لتر',
    category: 'Cleaning & Hygiene',
    subCategory: 'Disinfectants',
    supplierId: 'sup-012',
    unit: 'unit',
    basePrice: 78,
    creditPrice: 82.68,
    moq: 6,
    sku: 'HV-CH-007',
    inStock: true,
    leadTime: 1,
    description: 'Hospital-grade surface disinfectant. Effective against bacteria and viruses. For kitchen counters, tables, and high-touch areas.',
  },
  {
    id: 'prod-048',
    name: 'Air Freshener (12pc)',
    nameAr: 'معطر جو (12 قطعة)',
    category: 'Cleaning & Hygiene',
    subCategory: 'Air Care',
    supplierId: 'sup-020',
    unit: 'case',
    basePrice: 65,
    creditPrice: 68.90,
    moq: 5,
    sku: 'HV-CH-008',
    inStock: true,
    leadTime: 2,
    description: 'Aerosol air freshener refills, 12 cans per case. Fresh linen scent. For automated dispensers in lobbies and restrooms.',
  },
];

// ------------------------------------------------------------------
// 4. VALUE PROPOSITIONS
// ------------------------------------------------------------------
export interface ValueProposition {
  id: string;
  audience: 'hotel' | 'supplier';
  title: string;
  description: string;
  icon: string;
}

export const hotelValuePropositions: ValueProposition[] = [
  {
    id: 'hv-1',
    audience: 'hotel',
    title: 'AI Demand Forecasting',
    description: 'Predict consumption 14 days ahead with 94% accuracy',
    icon: 'Brain',
  },
  {
    id: 'hv-2',
    audience: 'hotel',
    title: 'Multi-Property Consolidation',
    description: 'Manage procurement across all properties from one dashboard',
    icon: 'Building2',
  },
  {
    id: 'hv-3',
    audience: 'hotel',
    title: 'Embedded Financing',
    description: '30/60/90 day payment terms through licensed NBFI partners',
    icon: 'Wallet',
  },
  {
    id: 'hv-4',
    audience: 'hotel',
    title: 'ETA Auto-Compliance',
    description: 'Every invoice auto-submitted to Egyptian Tax Authority',
    icon: 'FileCheck',
  },
  {
    id: 'hv-5',
    audience: 'hotel',
    title: 'Price Benchmarking',
    description: 'Compare prices across suppliers in real time',
    icon: 'BarChart3',
  },
  {
    id: 'hv-6',
    audience: 'hotel',
    title: 'Quality Score Tracking',
    description: 'Rate suppliers on delivery, quality, and consistency',
    icon: 'Star',
  },
  {
    id: 'hv-7',
    audience: 'hotel',
    title: '48-Hour Delivery SLA',
    description: 'Guaranteed delivery windows with live tracking',
    icon: 'Truck',
  },
  {
    id: 'hv-8',
    audience: 'hotel',
    title: 'Authority Matrix',
    description: 'Multi-level approvals enforced at the database layer',
    icon: 'ShieldCheck',
  },
];

export const supplierValuePropositions: ValueProposition[] = [
  {
    id: 'sv-1',
    audience: 'supplier',
    title: 'Direct Hotel Network',
    description: 'Access 52+ verified hotel properties instantly',
    icon: 'Hotel',
  },
  {
    id: 'sv-2',
    audience: 'supplier',
    title: 'Instant Payment',
    description: 'Get paid in 48 hours, not 90 days',
    icon: 'Zap',
  },
  {
    id: 'sv-3',
    audience: 'supplier',
    title: 'Credit Line Management',
    description: 'Offer credit terms without taking the risk',
    icon: 'CreditCard',
  },
  {
    id: 'sv-4',
    audience: 'supplier',
    title: 'Automated Reconciliation',
    description: 'Auto-matched invoices and payments',
    icon: 'ClipboardCheck',
  },
  {
    id: 'sv-5',
    audience: 'supplier',
    title: 'Growth Analytics',
    description: 'See which hotels order most, when, and what',
    icon: 'TrendingUp',
  },
  {
    id: 'sv-6',
    audience: 'supplier',
    title: 'ETA Compliance Support',
    description: 'We handle e-invoice formatting and submission',
    icon: 'FileText',
  },
  {
    id: 'sv-7',
    audience: 'supplier',
    title: 'Bulk Order Aggregation',
    description: 'One PO, multiple properties, single delivery',
    icon: 'Package',
  },
  {
    id: 'sv-8',
    audience: 'supplier',
    title: 'Reduced DSO',
    description: 'Cut days sales outstanding from 90 to 48',
    icon: 'Clock',
  },
];

// ------------------------------------------------------------------
// 5. TRUST BADGES
// ------------------------------------------------------------------
export interface TrustBadge {
  id: string;
  title: string;
  description: string;
  icon: string;
}

export const trustBadges: TrustBadge[] = [
  {
    id: 'tb-1',
    title: 'ETA Tax Authority Certified',
    description: 'Full integration with Egyptian Tax Authority e-invoice system',
    icon: 'BadgeCheck',
  },
  {
    id: 'tb-2',
    title: 'ISO 27001 Information Security',
    description: 'Certified information security management system',
    icon: 'Shield',
  },
  {
    id: 'tb-3',
    title: 'Central Bank of Egypt Regulated',
    description: 'Operations supervised under CBE NBFI guidelines',
    icon: 'Landmark',
  },
  {
    id: 'tb-4',
    title: 'GDPR Compliant Data Handling',
    description: 'Enterprise-grade data privacy and protection',
    icon: 'Lock',
  },
  {
    id: 'tb-5',
    title: '256-Bit SSL Encryption',
    description: 'Bank-grade encryption for all data transmissions',
    icon: 'Key',
  },
  {
    id: 'tb-6',
    title: 'SOC 2 Type II Audited',
    description: 'Independent audit of security controls and processes',
    icon: 'FileSearch',
  },
  {
    id: 'tb-7',
    title: 'Verified Supplier Network',
    description: 'Every supplier vetted for registration and compliance',
    icon: 'Users',
  },
  {
    id: 'tb-8',
    title: 'Real-Time Transaction Monitoring',
    description: 'AI-powered fraud detection and anomaly alerts',
    icon: 'Activity',
  },
];

// ------------------------------------------------------------------
// 6. INVESTORS
// ------------------------------------------------------------------
export interface Investor {
  id: string;
  name: string;
  type: string;
  region: string;
  logoText: string;
}

export const investors: Investor[] = [
  {
    id: 'inv-1',
    name: 'Flat6Labs',
    type: 'VC',
    region: 'Egypt',
    logoText: 'F6',
  },
  {
    id: 'inv-2',
    name: 'Algebra Ventures',
    type: 'VC',
    region: 'Egypt',
    logoText: 'AV',
  },
  {
    id: 'inv-3',
    name: '500 Startups',
    type: 'VC',
    region: 'Global',
    logoText: '500',
  },
  {
    id: 'inv-4',
    name: 'Sawari Ventures',
    type: 'VC',
    region: 'MENA',
    logoText: 'SV',
  },
  {
    id: 'inv-5',
    name: 'Global Ventures',
    type: 'VC',
    region: 'MENA',
    logoText: 'GV',
  },
  {
    id: 'inv-6',
    name: 'A15',
    type: 'VC',
    region: 'Egypt',
    logoText: 'A15',
  },
];

// ------------------------------------------------------------------
// 7. WHO WE ARE
// ------------------------------------------------------------------
export interface TeamMember {
  name: string;
  role: string;
  bio: string;
}

export interface Milestone {
  year: string;
  event: string;
}

export interface CompanyValue {
  title: string;
  description: string;
}

export interface WhoWeAre {
  headline: string;
  story: string;
  mission: string;
  vision: string;
  values: CompanyValue[];
  team: TeamMember[];
  milestones: Milestone[];
}

export const whoWeAre: WhoWeAre = {
  headline: 'Built by Industry Veterans, For Industry Leaders',
  story: "Founded in 2024 by operators who spent 15+ years managing hotel procurement manually across Egypt's top properties. We built the platform we wished we had — one that understands the unique challenges of Egyptian hospitality.",
  mission: "To digitize Egypt's hospitality supply chain end-to-end, making procurement predictable, financing accessible, and compliance effortless for every hotel and supplier.",
  vision: 'To become the default operating system for hospitality procurement across the Middle East and Africa, starting with Egypt.',
  values: [
    {
      title: 'Transparency',
      description: 'Every price, every fee, every commission is visible. No hidden costs.',
    },
    {
      title: 'Innovation',
      description: 'We continuously invest in AI and automation to reduce friction.',
    },
    {
      title: 'Partnership',
      description: 'We succeed when our hotels and suppliers succeed.',
    },
    {
      title: 'Excellence',
      description: 'We hold ourselves to the same standards we demand from our network.',
    },
    {
      title: 'Compliance',
      description: 'Regulatory adherence is not optional — it is the foundation.',
    },
  ],
  team: [
    {
      name: 'Ahmed Hassan',
      role: 'Co-Founder & CEO',
      bio: '15+ years in hospitality operations across Cairo and Red Sea properties.',
    },
    {
      name: 'Mona El-Sayed',
      role: 'Co-Founder & CTO',
      bio: 'Former principal engineer at a leading fintech. Built payment systems processing EGP 2B+ annually.',
    },
    {
      name: 'Karim Fathi',
      role: 'Co-Founder & COO',
      bio: 'Supply chain expert with experience across GCC and Egyptian markets.',
    },
  ],
  milestones: [
    { year: '2024 Q1', event: 'Company founded in Cairo' },
    { year: '2024 Q2', event: 'First 10 hotel properties onboarded' },
    { year: '2024 Q3', event: 'ETA e-invoice integration live' },
    { year: '2024 Q4', event: 'EGP 10M monthly GMV reached' },
    { year: '2025 Q1', event: '52 hotels, 68 suppliers, EGP 86M GMV' },
  ],
};


export const categories = [
  { id: 'fresh-produce', name: 'Fresh Produce', nameAr: 'منتجات طازجة', icon: 'Salad', count: 234, color: '#22C55E' },
  { id: 'dairy-eggs', name: 'Dairy & Eggs', nameAr: 'ألبان وبيض', icon: 'Milk', count: 156, color: '#3B82F6' },
  { id: 'meat-poultry', name: 'Meat & Poultry', nameAr: 'لحوم ودواجن', icon: 'Beef', count: 189, color: '#EF4444' },
  { id: 'dry-goods', name: 'Dry Goods & Grains', nameAr: 'بضائع جافة وحبوب', icon: 'Wheat', count: 312, color: '#F59E0B' },
  { id: 'beverages', name: 'Beverages', nameAr: 'مشروبات', icon: 'Coffee', count: 127, color: '#8B5CF6' },
  { id: 'cleaning', name: 'Cleaning & Hygiene', nameAr: 'تنظيف ونظافة', icon: 'Sparkles', count: 98, color: '#14B8A6' },
];
