module.exports = {
  apps: [
    {
      name: "hotels-vendors",
      script: "server.js",
      cwd: "/var/www/hotelsvendors-v2/.next/standalone",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "development",
        PORT: 3003,
        HOST: "0.0.0.0",
      },
      env_production: {
        NODE_ENV: "production",
        PORT: 3003,
        HOST: "0.0.0.0",
        DATABASE_URL: "postgresql://hotels_vendors:DBPASS@localhost:5432/hotels_vendors?schema=public&connection_limit=10&pool_timeout=30",
        SESSION_SECRET: "3b7e2e5b7dd999deca3e3eb5f6a6ca5b547b6c59c56df567d9915bdbd0677830",
        HOTELSVENDORS_HMAC_SECRET: "3b7e2e5b7dd999deca3e3eb5f6a6ca5b547b6c59c56df567d9915bdbd0677830",
        REDIS_URL: "redis://:REDISPASS@localhost:6380",
        DATABASE_HOST: "localhost",
        DATABASE_PORT: "5432",
      },
      error_file: "/var/log/hotelsvendors/error.log",
      out_file: "/var/log/hotelsvendors/out.log",
      log_date_format: "YYYY-MM-DD HHmmss",
      merge_logs: true,
      max_memory_restart: "512M",
      restart_delay: 3000,
      max_restarts: 5,
      min_uptime: "10s",
      watch: false,
      kill_timeout: 5000,
      listen_timeout: 10000,
    },
    {
      name: "hotels-vendors-os",
      cwd: "/var/www/hotelsvendors-v2/backend_os",
      script: "/var/www/hotelsvendors-v2/backend_os/venv/bin/uvicorn",
      args: "src.main:app --host 0.0.0.0 --port 8001",
      exec_interpreter: "none",
      exec_mode: "fork",
      env_production: {
        PYTHONPATH: "/var/www/hotelsvendors-v2/backend_os",
        DB_HOST: "localhost",
        DB_PORT: "5432",
        DB_NAME: "hotels_vendors",
        DB_USERNAME: "hotels_vendors",
        DB_PASSWORD: "DBPASS",
        REDIS_HOST: "localhost",
        REDIS_PORT: "6380",
        REDIS_PASSWORD: "REDISPASS",
        DATABASE_URL: "postgresql://hotels_vendors:DBPASS@localhost:5432/hotels_vendors",
      },
      error_file: "/var/log/hotelsvendors-os/error.log",
      out_file: "/var/log/hotelsvendors-os/out.log",
      log_date_format: "YYYY-MM-DD HHmmss",
      merge_logs: true,
      restart_delay: 3000,
      max_restarts: 5,
      min_uptime: "10s",
      watch: false,
      kill_timeout: 5000,
      listen_timeout: 10000,
    },
    {
      name: "hv-sourcing-worker",
      cwd: "/var/www/hotelsvendors-v2",
      script: "/usr/bin/tsx",
      args: "scripts/queue-worker.ts",
      exec_interpreter: "none",
      exec_mode: "fork",
      instances: 1,
      env_production: {
        NODE_ENV: "production",
        REDIS_URL: "redis://:REDISPASS@localhost:6380",
        REDIS_HOST: "localhost",
        REDIS_PORT: "6380",
        REDIS_PASSWORD: "REDISPASS",
        DATABASE_URL: "postgresql://hotels_vendors:***@localhost:5432/hotels_vendors?schema=public",
        APIFY_API_TOKEN: "",
      },
      error_file: "/var/log/hotelsvendors/worker-error.log",
      out_file: "/var/log/hotelsvendors/worker-out.log",
      log_date_format: "YYYY-MM-DD HHmmss",
      merge_logs: true,
      restart_delay: 3000,
      max_restarts: 5,
      max_memory_restart: "256M",
      kill_timeout: 5000,
    },
  ],
};
