import fs from "fs";
import path from "path";
import matter from "gray-matter";

const BLOG_DIR = path.join(process.cwd(), "content", "blog");
const OUT_FILE = path.join(process.cwd(), "lib", "blog-data.ts");

if (!fs.existsSync(BLOG_DIR)) {
  console.log("[generate-blog-data] No content/blog directory found, skipping");
  process.exit(0);
}

const files = fs.readdirSync(BLOG_DIR).filter((f) => f.endsWith(".md"));
const posts = files.map((file) => {
  const slug = file.replace(/\.md$/, "");
  const raw = fs.readFileSync(path.join(BLOG_DIR, file), "utf-8");
  const { data, content } = matter(raw);
  return {
    slug,
    title: data.title || "",
    titleAr: data.titleAr || "",
    description: data.description || "",
    descriptionAr: data.descriptionAr || "",
    date: data.date || new Date().toISOString(),
    author: data.author || "HotelsVendors Team",
    category: data.category || "Platform",
    categoryAr: data.categoryAr || "المنصة",
    tags: data.tags || [],
    readTime: Math.max(1, Math.ceil(content.split(/\s+/).length / 200)),
    featured: data.featured || false,
    content,
  };
});

const output = `// AUTO-GENERATED by scripts/generate-blog-data.ts — DO NOT EDIT
export interface BlogPost {
  slug: string;
  title: string;
  titleAr: string;
  description: string;
  descriptionAr: string;
  date: string;
  author: string;
  category: string;
  categoryAr: string;
  tags: string[];
  readTime: number;
  featured: boolean;
  content: string;
}

export const BLOG_POSTS: BlogPost[] = ${JSON.stringify(posts, null, 2)};

export function getAllPosts(): BlogPost[] {
  return [...BLOG_POSTS].sort((a, b) => (a.date > b.date ? -1 : 1));
}

export function getPostBySlug(slug: string): BlogPost | null {
  return BLOG_POSTS.find((p) => p.slug === slug) || null;
}

export function getAllSlugs(): string[] {
  return BLOG_POSTS.map((p) => p.slug);
}

export function getFeaturedPosts(): BlogPost[] {
  return BLOG_POSTS.filter((p) => p.featured);
}

export function getPostsByCategory(category: string): BlogPost[] {
  return BLOG_POSTS.filter((p) => p.category.toLowerCase() === category.toLowerCase());
}

export function getAllCategories(): string[] {
  return [...new Set(BLOG_POSTS.map((p) => p.category))];
}
`;

fs.writeFileSync(OUT_FILE, output);
console.log(`[generate-blog-data] Generated ${OUT_FILE} with ${posts.length} posts`);
